### ISSUE TITLE
Speech from opposite faction players is always very dark

### ISSUE THREAD

**Issue by Maia-Everett** [Kvalyr/KvChatDistance#1]
I'm logged on an Alliance character and listening to an Alliance and Horde character standing at the same distance from me talk to each other. The Horde character's speech is so dark it's illegible.

I have the Cross RP addon active, if that's important.

![image](https://user-images.githubusercontent.com/10684/105881332-f03d9400-6036-11eb-9405-69daeddd8d92.png)

**Comment by Kvalyr** [comment]
The colour of the chat for distant speakers is configurable in the addon's options (Esc menu -> Interface -> Addons -> Darken Chat Messages).

The 0.3.0 release should improve handling of opposite-faction chat in general.

Closing issue, but feel free to reopen if you find that it's still a substantial problem with 0.3.0.
